---
- name: debug the  full list
  debug:
    var: list_of_updates

- name: Template Rendering Indivisual Report
  template:
    src: win_update_dict.j2
    dest: "reports/z{{ inventory_hostname }}_interim_report.json"
  delegate_to: localhost

- name: Create Interim Report Header
  template:
    src: win_update_report_header.j2
    dest: "reports/Consolidated_VMs_Report.json"
  delegate_to: localhost
  run_once: yes

- name: Consolidate Interim Reports with Header
  assemble:
    src: reports/
    dest: reports/Consolidated_VMs_Report.json
  delegate_to: localhost
  run_once: yes

- name: Generate Remaining Portion of Report
  template:
    src: win_update_report_footer.j2
    dest: "reports/consolidated_vms_report_last_block.json"
  delegate_to: localhost
  run_once: yes

- name: Get the List of Interim Reports
  find:
    paths: reports/
    patterns: '*_interim_report.json'
  register: interim_reports_to_delete
  delegate_to: localhost
  run_once: yes

- name: Clean Up Interim Reports
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ interim_reports_to_delete.files }}"
  delegate_to: localhost
  run_once: yes

- name: Consolidate Final Report
  assemble:
    src: reports/
    dest: reports/Consolidated_VMs_Report.json
  delegate_to: localhost
  run_once: yes

- name: Final Clean Up
  file:
    path: reports/consolidated_vms_report_last_block.json
    state: absent
  delegate_to: localhost
  run_once: yes  

- name: Send Email with Report
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: "{{ sendto_email }}"
    subject: "Ansible Report"
    body: "The new consolidated json data structure in a file"
    attach:
     - reports/Consolidated_VMs_Report.json
  delegate_to: localhost
  run_once: yes  