---
- name: Clean Up Reports Directory if it exists
  file:
    path: {{ items }}
    state: absent
  with_items: 
    - reports
    - /tmp/reports  
  delegate_to: localhost
  run_once: yes

- name: Create Reports Directory
  file:
    path: reports
    state: directory
    mode: 0755
  delegate_to: localhost
  run_once: yes

- name: debug the  full list
  debug:
    var: list_of_updates.found_update_count

- name: Template Rendering Indivisual Report
  template:
    src: win_update_dict.j2
    dest: "reports/{{ inventory_hostname }}_interim_report.json"
  delegate_to: localhost
  when: list_of_updates.found_update_count != 0

- name: Consolidate Interim Reports only
  assemble:
    src: reports/
    dest: /tmp/reports/ansible_data.json
  delegate_to: localhost
  run_once: yes

#- name: Create Interim file Header
#  template:
#    src: win_update_report_header.j2
#    dest: "reports/zjson_header.json"
#  delegate_to: localhost
#  run_once: yes

#- name: Generate footer of file
#  template:
#    src: win_update_report_footer.j2
#    dest: "reports/zzzjson_footer.json"
#  delegate_to: localhost
#  run_once: yes

- name: Get the List of Interim Reports
  find:
    paths: reports/
    patterns: '*_interim_report.json'
  register: interim_reports_to_delete
  delegate_to: localhost
  run_once: yes

- name: Clean Up Interim Reports
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ interim_reports_to_delete.files }}"
  delegate_to: localhost
  run_once: yes

#- name: Consolidate Final Report
#  assemble:
#    src: reports/
#    dest: reports/ansible_data.json
#  delegate_to: localhost
#  run_once: yes

#- name: Final Clean Up
#  file:
#    path: reports/zzzjson_footer.json
#    state: absent
#  delegate_to: localhost
#  run_once: yes  

- name: Send Email with Report
  mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ gmail_account }}"
    password: "{{ gmail_account_password }}"
    to: "{{ sendto_email }}"
    subject: "Ansible Report"
    body: "The new consolidated json data structure in a file"
    attach:
     - /tmp/reports/ansible_data.json
  delegate_to: localhost
  run_once: yes  